# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91e100d84659c7ff64decd99693a9a2c70c1355084222c885372d1a7095d20b7a67c0d6f41725c9a6dbecb29ca54036dc8db0b24eff22e7c82281267fbee547a

test:
  secret_key_base: 95e50829b6b1ceb7eacd4c438892b1b9562e34d8454a99ad7c5838b9d5f3d3c9bc8ee821d92e39ef22c072128f38d643cd73584f0775f8dcb830e0122d89e326

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
